base_url = "https://moolicc.github.io/"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
theme = "Zulma"
paginate_by = 5
taxonomies = [
    { name = "projects" },
    { name = "tags", rss = true, paginate_by = 5 },
]

[markdown]
highlight_code = true
render_emoji = true
smart_punctuation = true
highlight_theme = "base16-ocean-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"


[extra]
zulma_menu = [
    { url = "$BASE_URLprojects", name = "Projects" },
    { sep = true },
    { url = "$BASE_URLblog", name = "All Posts" },
    { url = "$BASE_URLtags", name = "Tags" },
]
zulma_brand = { text = "Home" }
zulma_theme = "lux"
zulma_allow_theme_selection = false
