
name: Add gist post

on:
  workflow_dispatch:
    inputs:
      file-name:
        description: 'Name of the gist file'     
        required: true

env:
  GIST_OWNER: 'moolicc'
  GIST_DESC_TARGET: 'posts'

jobs:
  post-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap post from gist
        uses: satackey/action-js-inline@release-master
        id: getdata
        with:
          required-packages: axios
          script: |
            const core = require('@actions/core');
            const axios = require('axios');
            console.log("dgfsdg");
            
            var owner = '${{ env.GIST_OWNER }}'
            var desc = '${{ env.GIST_DESC_TARGET }}'
            console.log(`Awaiting response from https://api.github.com/users/${owner}/gists`);
            const response = await axios(`https://api.github.com/users/${owner}/gists`);
            
            console.log("Response gotten");
            console.log(desc);
            console.log(response);
            
            for(var gist in response) {
              
              if(gist.description == desc) {
                console.log("YEP");
              }
              else {
                console.log(gist["description"]);
              }
            }
            
            var url = "";
            
            core.exportVariable('MD_URL', url);
